### ISSUE TITLE
Авторизация в extern-kontur

### ISSUE THREAD

**Issue by allengosta2010** [skbkontur/extern-api-docs#8]
Подскажите, пожалуйста, каким методом авторизоваться в extern.kontur?
Имею в виду сайт - https://auth.kontur.ru/?back=https%3a%2f%2fsetter.kontur.ru%2f%3ffrom_keweb%3dextern.kontur.ru%252f
Пробую таким способом:

import requests
import json

headers = {
    'Content-type': "application/json; charset=UTF-8",
    'User-Agent': 'Test',
    'Cache-Control': "no-cache"
}

session = requests.Session()
session.verify = False
session.cookies.get_dict()

data = {'login': "login", 'password': "password"}

resp = session.post("https://extern.kontur.ru/auth/v5.13/authenticate-by-pass/", data=json.dumps(data), headers=headers)

print("sid = ", session.cookies['sid'])

**Comment by NazarovDmitry** [comment]
Добрый день!

Аутентификация по логину и паролю описана в документации: https://developer.kontur.ru/auth. Если вы подключили АПИ, то вам должны были предоставить данные для входа.
Вопросы по апи лучше задавать на почту: extern-api.help@skbkontur.ru.
